---
cache: cargo
dist: xenial
install: 
  - "source ~/.cargo/env || true"
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - "cargo test"
  - "cargo run --example add"
  - "cargo run --example concat"
  - "cargo run --example ensemble"
  - "cargo run --example mean_reverse"
  - "cargo run --example stddev"
sudo: required
