---
cache: cargo
dist: xenial
install: 
  - "source ~/.cargo/env || true"
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - "cargo test"
sudo: required
